# -*- coding: utf-8 -*-
"""Placement_Langchain.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mpAnGGNWd2dKhpWJkQ-SYjXhnnzRYNY-
"""

!pip install langchain-classic
!pip install langchain-groq
from langchain_community.document_loaders import TextLoader
from langchain_text_splitters import CharacterTextSplitter
from langchain_community.embeddings import HuggingFaceEmbeddings
from langchain_community.vectorstores import FAISS
from langchain_classic.chains import RetrievalQA
from langchain_groq import ChatGroq
import os

loader = TextLoader("/content/notes.txt")
documents = loader.load()

splitter = CharacterTextSplitter(chunk_size=500,chunk_overlap=50)
docs = splitter.split_documents(documents)

!pip install faiss-cpu
embeddings = HuggingFaceEmbeddings()
vectorstore = FAISS.from_documents(docs,embeddings)

# Set your Groq API key.
os.environ["GROQ_API_KEY"] = "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"

# Initialize llm and qa_chain with the Groq model, specifying a model_name
llm = ChatGroq(groq_api_key=os.environ["GROQ_API_KEY"], model_name='llama-3.3-70b-versatile')
qa_chain = RetrievalQA.from_chain_type(
    llm=llm,
    retriever=vectorstore.as_retriever()
)

question = "What is love"
result = qa_chain.run(question)

print("Answer:",result)

